//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4206
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnityBO.DTO
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductDTO", Namespace="http://schemas.datacontract.org/2004/07/UnityBO.DTO")]
    public partial class ProductDTO : UnityBO.DTO.DTOObjectBase
    {
        
        private string ClassField;
        
        private string ColorField;
        
        private int DaysToManufactureField;
        
        private decimal ListPriceField;
        
        private System.DateTime ModifiedDateField;
        
        private string NameField;
        
        private int ProductIdField;
        
        private string ProductNumberField;
        
        private string StyleField;
        
        private int SubcategoryIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Class
        {
            get
            {
                return this.ClassField;
            }
            set
            {
                this.ClassField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color
        {
            get
            {
                return this.ColorField;
            }
            set
            {
                this.ColorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DaysToManufacture
        {
            get
            {
                return this.DaysToManufactureField;
            }
            set
            {
                this.DaysToManufactureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ListPrice
        {
            get
            {
                return this.ListPriceField;
            }
            set
            {
                this.ListPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate
        {
            get
            {
                return this.ModifiedDateField;
            }
            set
            {
                this.ModifiedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId
        {
            get
            {
                return this.ProductIdField;
            }
            set
            {
                this.ProductIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductNumber
        {
            get
            {
                return this.ProductNumberField;
            }
            set
            {
                this.ProductNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Style
        {
            get
            {
                return this.StyleField;
            }
            set
            {
                this.StyleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubcategoryId
        {
            get
            {
                return this.SubcategoryIdField;
            }
            set
            {
                this.SubcategoryIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOObjectBase", Namespace="http://schemas.datacontract.org/2004/07/UnityBO.DTO")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UnityBO.DTO.ProductSubcategoryDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UnityBO.DTO.ProductCategoryDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UnityBO.DTO.ProductDTO))]
    public partial class DTOObjectBase : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductSubcategoryDTO", Namespace="http://schemas.datacontract.org/2004/07/UnityBO.DTO")]
    public partial class ProductSubcategoryDTO : UnityBO.DTO.DTOObjectBase
    {
        
        private System.Guid IdField;
        
        private string NameField;
        
        private int ProductCategoryIdField;
        
        private int ProductSubcategoryIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductCategoryId
        {
            get
            {
                return this.ProductCategoryIdField;
            }
            set
            {
                this.ProductCategoryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductSubcategoryId
        {
            get
            {
                return this.ProductSubcategoryIdField;
            }
            set
            {
                this.ProductSubcategoryIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductCategoryDTO", Namespace="http://schemas.datacontract.org/2004/07/UnityBO.DTO")]
    public partial class ProductCategoryDTO : UnityBO.DTO.DTOObjectBase
    {
        
        private string NameField;
        
        private int ProductCategoryIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductCategoryId
        {
            get
            {
                return this.ProductCategoryIdField;
            }
            set
            {
                this.ProductCategoryIdField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://kettenba.ch", ConfigurationName="IProductService")]
public interface IProductService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://kettenba.ch/IProductService/GetProducts", ReplyAction="http://kettenba.ch/IProductService/GetProductsResponse")]
    UnityBO.DTO.ProductDTO[] GetProducts();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://kettenba.ch/IProductService/GetProduct", ReplyAction="http://kettenba.ch/IProductService/GetProductResponse")]
    UnityBO.DTO.ProductDTO GetProduct(int productId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://kettenba.ch/IProductService/GetProductsBySubcategory", ReplyAction="http://kettenba.ch/IProductService/GetProductsBySubcategoryResponse")]
    UnityBO.DTO.ProductDTO[] GetProductsBySubcategory(UnityBO.DTO.ProductSubcategoryDTO subcategory);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://kettenba.ch/IProductService/GetCategories", ReplyAction="http://kettenba.ch/IProductService/GetCategoriesResponse")]
    UnityBO.DTO.ProductCategoryDTO[] GetCategories();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://kettenba.ch/IProductService/GetSubcategories", ReplyAction="http://kettenba.ch/IProductService/GetSubcategoriesResponse")]
    UnityBO.DTO.ProductSubcategoryDTO[] GetSubcategories();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://kettenba.ch/IProductService/GetSubcategoriesByCategory", ReplyAction="http://kettenba.ch/IProductService/GetSubcategoriesByCategoryResponse")]
    UnityBO.DTO.ProductSubcategoryDTO[] GetSubcategoriesByCategory(UnityBO.DTO.ProductCategoryDTO category);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IProductServiceChannel : IProductService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class ProductServiceClient : System.ServiceModel.ClientBase<IProductService>, IProductService
{
    
    public ProductServiceClient()
    {
    }
    
    public ProductServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ProductServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ProductServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ProductServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public UnityBO.DTO.ProductDTO[] GetProducts()
    {
        return base.Channel.GetProducts();
    }
    
    public UnityBO.DTO.ProductDTO GetProduct(int productId)
    {
        return base.Channel.GetProduct(productId);
    }
    
    public UnityBO.DTO.ProductDTO[] GetProductsBySubcategory(UnityBO.DTO.ProductSubcategoryDTO subcategory)
    {
        return base.Channel.GetProductsBySubcategory(subcategory);
    }
    
    public UnityBO.DTO.ProductCategoryDTO[] GetCategories()
    {
        return base.Channel.GetCategories();
    }
    
    public UnityBO.DTO.ProductSubcategoryDTO[] GetSubcategories()
    {
        return base.Channel.GetSubcategories();
    }
    
    public UnityBO.DTO.ProductSubcategoryDTO[] GetSubcategoriesByCategory(UnityBO.DTO.ProductCategoryDTO category)
    {
        return base.Channel.GetSubcategoriesByCategory(category);
    }
}
