//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4206
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 3.0.40624.0
// 
namespace UnitySilverlightApp.ProductService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductDTO", Namespace="http://schemas.datacontract.org/2004/07/UnityBO.DTO")]
    public partial class ProductDTO : UnitySilverlightApp.ProductService.DTOObjectBase {
        
        private string ClassField;
        
        private string ColorField;
        
        private int DaysToManufactureField;
        
        private decimal ListPriceField;
        
        private System.DateTime ModifiedDateField;
        
        private string NameField;
        
        private int ProductIdField;
        
        private string ProductNumberField;
        
        private string StyleField;
        
        private int SubcategoryIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Class {
            get {
                return this.ClassField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassField, value) != true)) {
                    this.ClassField = value;
                    this.RaisePropertyChanged("Class");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DaysToManufacture {
            get {
                return this.DaysToManufactureField;
            }
            set {
                if ((this.DaysToManufactureField.Equals(value) != true)) {
                    this.DaysToManufactureField = value;
                    this.RaisePropertyChanged("DaysToManufacture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ListPrice {
            get {
                return this.ListPriceField;
            }
            set {
                if ((this.ListPriceField.Equals(value) != true)) {
                    this.ListPriceField = value;
                    this.RaisePropertyChanged("ListPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductNumber {
            get {
                return this.ProductNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNumberField, value) != true)) {
                    this.ProductNumberField = value;
                    this.RaisePropertyChanged("ProductNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Style {
            get {
                return this.StyleField;
            }
            set {
                if ((object.ReferenceEquals(this.StyleField, value) != true)) {
                    this.StyleField = value;
                    this.RaisePropertyChanged("Style");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubcategoryId {
            get {
                return this.SubcategoryIdField;
            }
            set {
                if ((this.SubcategoryIdField.Equals(value) != true)) {
                    this.SubcategoryIdField = value;
                    this.RaisePropertyChanged("SubcategoryId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOObjectBase", Namespace="http://schemas.datacontract.org/2004/07/UnityBO.DTO")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UnitySilverlightApp.ProductService.ProductSubcategoryDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UnitySilverlightApp.ProductService.ProductCategoryDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UnitySilverlightApp.ProductService.ProductDTO))]
    public partial class DTOObjectBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductSubcategoryDTO", Namespace="http://schemas.datacontract.org/2004/07/UnityBO.DTO")]
    public partial class ProductSubcategoryDTO : UnitySilverlightApp.ProductService.DTOObjectBase {
        
        private string NameField;
        
        private int ProductCategoryIdField;
        
        private int ProductSubcategoryIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductCategoryId {
            get {
                return this.ProductCategoryIdField;
            }
            set {
                if ((this.ProductCategoryIdField.Equals(value) != true)) {
                    this.ProductCategoryIdField = value;
                    this.RaisePropertyChanged("ProductCategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductSubcategoryId {
            get {
                return this.ProductSubcategoryIdField;
            }
            set {
                if ((this.ProductSubcategoryIdField.Equals(value) != true)) {
                    this.ProductSubcategoryIdField = value;
                    this.RaisePropertyChanged("ProductSubcategoryId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductCategoryDTO", Namespace="http://schemas.datacontract.org/2004/07/UnityBO.DTO")]
    public partial class ProductCategoryDTO : UnitySilverlightApp.ProductService.DTOObjectBase {
        
        private string NameField;
        
        private int ProductCategoryIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductCategoryId {
            get {
                return this.ProductCategoryIdField;
            }
            set {
                if ((this.ProductCategoryIdField.Equals(value) != true)) {
                    this.ProductCategoryIdField = value;
                    this.RaisePropertyChanged("ProductCategoryId");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://kettenba.ch", ConfigurationName="ProductService.IProductService")]
    public interface IProductService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://kettenba.ch/IProductService/GetProducts", ReplyAction="http://kettenba.ch/IProductService/GetProductsResponse")]
        System.IAsyncResult BeginGetProducts(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductDTO> EndGetProducts(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://kettenba.ch/IProductService/GetProduct", ReplyAction="http://kettenba.ch/IProductService/GetProductResponse")]
        System.IAsyncResult BeginGetProduct(int productId, System.AsyncCallback callback, object asyncState);
        
        UnitySilverlightApp.ProductService.ProductDTO EndGetProduct(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://kettenba.ch/IProductService/GetProductsBySubcategory", ReplyAction="http://kettenba.ch/IProductService/GetProductsBySubcategoryResponse")]
        System.IAsyncResult BeginGetProductsBySubcategory(UnitySilverlightApp.ProductService.ProductSubcategoryDTO subcategory, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductDTO> EndGetProductsBySubcategory(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://kettenba.ch/IProductService/GetCategories", ReplyAction="http://kettenba.ch/IProductService/GetCategoriesResponse")]
        System.IAsyncResult BeginGetCategories(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductCategoryDTO> EndGetCategories(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://kettenba.ch/IProductService/GetSubcategories", ReplyAction="http://kettenba.ch/IProductService/GetSubcategoriesResponse")]
        System.IAsyncResult BeginGetSubcategories(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductSubcategoryDTO> EndGetSubcategories(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://kettenba.ch/IProductService/GetSubcategoriesByCategory", ReplyAction="http://kettenba.ch/IProductService/GetSubcategoriesByCategoryResponse")]
        System.IAsyncResult BeginGetSubcategoriesByCategory(UnitySilverlightApp.ProductService.ProductCategoryDTO category, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductSubcategoryDTO> EndGetSubcategoriesByCategory(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IProductServiceChannel : UnitySilverlightApp.ProductService.IProductService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetProductsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetProductsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductDTO> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductDTO>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public UnitySilverlightApp.ProductService.ProductDTO Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((UnitySilverlightApp.ProductService.ProductDTO)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetProductsBySubcategoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetProductsBySubcategoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductDTO> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductDTO>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetCategoriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCategoriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductCategoryDTO> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductCategoryDTO>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetSubcategoriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSubcategoriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductSubcategoryDTO> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductSubcategoryDTO>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetSubcategoriesByCategoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSubcategoriesByCategoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductSubcategoryDTO> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductSubcategoryDTO>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ProductServiceClient : System.ServiceModel.ClientBase<UnitySilverlightApp.ProductService.IProductService>, UnitySilverlightApp.ProductService.IProductService {
        
        private BeginOperationDelegate onBeginGetProductsDelegate;
        
        private EndOperationDelegate onEndGetProductsDelegate;
        
        private System.Threading.SendOrPostCallback onGetProductsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetProductDelegate;
        
        private EndOperationDelegate onEndGetProductDelegate;
        
        private System.Threading.SendOrPostCallback onGetProductCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetProductsBySubcategoryDelegate;
        
        private EndOperationDelegate onEndGetProductsBySubcategoryDelegate;
        
        private System.Threading.SendOrPostCallback onGetProductsBySubcategoryCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetCategoriesDelegate;
        
        private EndOperationDelegate onEndGetCategoriesDelegate;
        
        private System.Threading.SendOrPostCallback onGetCategoriesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetSubcategoriesDelegate;
        
        private EndOperationDelegate onEndGetSubcategoriesDelegate;
        
        private System.Threading.SendOrPostCallback onGetSubcategoriesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetSubcategoriesByCategoryDelegate;
        
        private EndOperationDelegate onEndGetSubcategoriesByCategoryDelegate;
        
        private System.Threading.SendOrPostCallback onGetSubcategoriesByCategoryCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ProductServiceClient() {
        }
        
        public ProductServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetProductsCompletedEventArgs> GetProductsCompleted;
        
        public event System.EventHandler<GetProductCompletedEventArgs> GetProductCompleted;
        
        public event System.EventHandler<GetProductsBySubcategoryCompletedEventArgs> GetProductsBySubcategoryCompleted;
        
        public event System.EventHandler<GetCategoriesCompletedEventArgs> GetCategoriesCompleted;
        
        public event System.EventHandler<GetSubcategoriesCompletedEventArgs> GetSubcategoriesCompleted;
        
        public event System.EventHandler<GetSubcategoriesByCategoryCompletedEventArgs> GetSubcategoriesByCategoryCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult UnitySilverlightApp.ProductService.IProductService.BeginGetProducts(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetProducts(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductDTO> UnitySilverlightApp.ProductService.IProductService.EndGetProducts(System.IAsyncResult result) {
            return base.Channel.EndGetProducts(result);
        }
        
        private System.IAsyncResult OnBeginGetProducts(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((UnitySilverlightApp.ProductService.IProductService)(this)).BeginGetProducts(callback, asyncState);
        }
        
        private object[] OnEndGetProducts(System.IAsyncResult result) {
            System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductDTO> retVal = ((UnitySilverlightApp.ProductService.IProductService)(this)).EndGetProducts(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetProductsCompleted(object state) {
            if ((this.GetProductsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetProductsCompleted(this, new GetProductsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetProductsAsync() {
            this.GetProductsAsync(null);
        }
        
        public void GetProductsAsync(object userState) {
            if ((this.onBeginGetProductsDelegate == null)) {
                this.onBeginGetProductsDelegate = new BeginOperationDelegate(this.OnBeginGetProducts);
            }
            if ((this.onEndGetProductsDelegate == null)) {
                this.onEndGetProductsDelegate = new EndOperationDelegate(this.OnEndGetProducts);
            }
            if ((this.onGetProductsCompletedDelegate == null)) {
                this.onGetProductsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetProductsCompleted);
            }
            base.InvokeAsync(this.onBeginGetProductsDelegate, null, this.onEndGetProductsDelegate, this.onGetProductsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult UnitySilverlightApp.ProductService.IProductService.BeginGetProduct(int productId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetProduct(productId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitySilverlightApp.ProductService.ProductDTO UnitySilverlightApp.ProductService.IProductService.EndGetProduct(System.IAsyncResult result) {
            return base.Channel.EndGetProduct(result);
        }
        
        private System.IAsyncResult OnBeginGetProduct(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int productId = ((int)(inValues[0]));
            return ((UnitySilverlightApp.ProductService.IProductService)(this)).BeginGetProduct(productId, callback, asyncState);
        }
        
        private object[] OnEndGetProduct(System.IAsyncResult result) {
            UnitySilverlightApp.ProductService.ProductDTO retVal = ((UnitySilverlightApp.ProductService.IProductService)(this)).EndGetProduct(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetProductCompleted(object state) {
            if ((this.GetProductCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetProductCompleted(this, new GetProductCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetProductAsync(int productId) {
            this.GetProductAsync(productId, null);
        }
        
        public void GetProductAsync(int productId, object userState) {
            if ((this.onBeginGetProductDelegate == null)) {
                this.onBeginGetProductDelegate = new BeginOperationDelegate(this.OnBeginGetProduct);
            }
            if ((this.onEndGetProductDelegate == null)) {
                this.onEndGetProductDelegate = new EndOperationDelegate(this.OnEndGetProduct);
            }
            if ((this.onGetProductCompletedDelegate == null)) {
                this.onGetProductCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetProductCompleted);
            }
            base.InvokeAsync(this.onBeginGetProductDelegate, new object[] {
                        productId}, this.onEndGetProductDelegate, this.onGetProductCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult UnitySilverlightApp.ProductService.IProductService.BeginGetProductsBySubcategory(UnitySilverlightApp.ProductService.ProductSubcategoryDTO subcategory, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetProductsBySubcategory(subcategory, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductDTO> UnitySilverlightApp.ProductService.IProductService.EndGetProductsBySubcategory(System.IAsyncResult result) {
            return base.Channel.EndGetProductsBySubcategory(result);
        }
        
        private System.IAsyncResult OnBeginGetProductsBySubcategory(object[] inValues, System.AsyncCallback callback, object asyncState) {
            UnitySilverlightApp.ProductService.ProductSubcategoryDTO subcategory = ((UnitySilverlightApp.ProductService.ProductSubcategoryDTO)(inValues[0]));
            return ((UnitySilverlightApp.ProductService.IProductService)(this)).BeginGetProductsBySubcategory(subcategory, callback, asyncState);
        }
        
        private object[] OnEndGetProductsBySubcategory(System.IAsyncResult result) {
            System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductDTO> retVal = ((UnitySilverlightApp.ProductService.IProductService)(this)).EndGetProductsBySubcategory(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetProductsBySubcategoryCompleted(object state) {
            if ((this.GetProductsBySubcategoryCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetProductsBySubcategoryCompleted(this, new GetProductsBySubcategoryCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetProductsBySubcategoryAsync(UnitySilverlightApp.ProductService.ProductSubcategoryDTO subcategory) {
            this.GetProductsBySubcategoryAsync(subcategory, null);
        }
        
        public void GetProductsBySubcategoryAsync(UnitySilverlightApp.ProductService.ProductSubcategoryDTO subcategory, object userState) {
            if ((this.onBeginGetProductsBySubcategoryDelegate == null)) {
                this.onBeginGetProductsBySubcategoryDelegate = new BeginOperationDelegate(this.OnBeginGetProductsBySubcategory);
            }
            if ((this.onEndGetProductsBySubcategoryDelegate == null)) {
                this.onEndGetProductsBySubcategoryDelegate = new EndOperationDelegate(this.OnEndGetProductsBySubcategory);
            }
            if ((this.onGetProductsBySubcategoryCompletedDelegate == null)) {
                this.onGetProductsBySubcategoryCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetProductsBySubcategoryCompleted);
            }
            base.InvokeAsync(this.onBeginGetProductsBySubcategoryDelegate, new object[] {
                        subcategory}, this.onEndGetProductsBySubcategoryDelegate, this.onGetProductsBySubcategoryCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult UnitySilverlightApp.ProductService.IProductService.BeginGetCategories(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCategories(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductCategoryDTO> UnitySilverlightApp.ProductService.IProductService.EndGetCategories(System.IAsyncResult result) {
            return base.Channel.EndGetCategories(result);
        }
        
        private System.IAsyncResult OnBeginGetCategories(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((UnitySilverlightApp.ProductService.IProductService)(this)).BeginGetCategories(callback, asyncState);
        }
        
        private object[] OnEndGetCategories(System.IAsyncResult result) {
            System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductCategoryDTO> retVal = ((UnitySilverlightApp.ProductService.IProductService)(this)).EndGetCategories(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCategoriesCompleted(object state) {
            if ((this.GetCategoriesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCategoriesCompleted(this, new GetCategoriesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCategoriesAsync() {
            this.GetCategoriesAsync(null);
        }
        
        public void GetCategoriesAsync(object userState) {
            if ((this.onBeginGetCategoriesDelegate == null)) {
                this.onBeginGetCategoriesDelegate = new BeginOperationDelegate(this.OnBeginGetCategories);
            }
            if ((this.onEndGetCategoriesDelegate == null)) {
                this.onEndGetCategoriesDelegate = new EndOperationDelegate(this.OnEndGetCategories);
            }
            if ((this.onGetCategoriesCompletedDelegate == null)) {
                this.onGetCategoriesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCategoriesCompleted);
            }
            base.InvokeAsync(this.onBeginGetCategoriesDelegate, null, this.onEndGetCategoriesDelegate, this.onGetCategoriesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult UnitySilverlightApp.ProductService.IProductService.BeginGetSubcategories(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSubcategories(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductSubcategoryDTO> UnitySilverlightApp.ProductService.IProductService.EndGetSubcategories(System.IAsyncResult result) {
            return base.Channel.EndGetSubcategories(result);
        }
        
        private System.IAsyncResult OnBeginGetSubcategories(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((UnitySilverlightApp.ProductService.IProductService)(this)).BeginGetSubcategories(callback, asyncState);
        }
        
        private object[] OnEndGetSubcategories(System.IAsyncResult result) {
            System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductSubcategoryDTO> retVal = ((UnitySilverlightApp.ProductService.IProductService)(this)).EndGetSubcategories(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSubcategoriesCompleted(object state) {
            if ((this.GetSubcategoriesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSubcategoriesCompleted(this, new GetSubcategoriesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSubcategoriesAsync() {
            this.GetSubcategoriesAsync(null);
        }
        
        public void GetSubcategoriesAsync(object userState) {
            if ((this.onBeginGetSubcategoriesDelegate == null)) {
                this.onBeginGetSubcategoriesDelegate = new BeginOperationDelegate(this.OnBeginGetSubcategories);
            }
            if ((this.onEndGetSubcategoriesDelegate == null)) {
                this.onEndGetSubcategoriesDelegate = new EndOperationDelegate(this.OnEndGetSubcategories);
            }
            if ((this.onGetSubcategoriesCompletedDelegate == null)) {
                this.onGetSubcategoriesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSubcategoriesCompleted);
            }
            base.InvokeAsync(this.onBeginGetSubcategoriesDelegate, null, this.onEndGetSubcategoriesDelegate, this.onGetSubcategoriesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult UnitySilverlightApp.ProductService.IProductService.BeginGetSubcategoriesByCategory(UnitySilverlightApp.ProductService.ProductCategoryDTO category, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSubcategoriesByCategory(category, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductSubcategoryDTO> UnitySilverlightApp.ProductService.IProductService.EndGetSubcategoriesByCategory(System.IAsyncResult result) {
            return base.Channel.EndGetSubcategoriesByCategory(result);
        }
        
        private System.IAsyncResult OnBeginGetSubcategoriesByCategory(object[] inValues, System.AsyncCallback callback, object asyncState) {
            UnitySilverlightApp.ProductService.ProductCategoryDTO category = ((UnitySilverlightApp.ProductService.ProductCategoryDTO)(inValues[0]));
            return ((UnitySilverlightApp.ProductService.IProductService)(this)).BeginGetSubcategoriesByCategory(category, callback, asyncState);
        }
        
        private object[] OnEndGetSubcategoriesByCategory(System.IAsyncResult result) {
            System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductSubcategoryDTO> retVal = ((UnitySilverlightApp.ProductService.IProductService)(this)).EndGetSubcategoriesByCategory(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSubcategoriesByCategoryCompleted(object state) {
            if ((this.GetSubcategoriesByCategoryCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSubcategoriesByCategoryCompleted(this, new GetSubcategoriesByCategoryCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSubcategoriesByCategoryAsync(UnitySilverlightApp.ProductService.ProductCategoryDTO category) {
            this.GetSubcategoriesByCategoryAsync(category, null);
        }
        
        public void GetSubcategoriesByCategoryAsync(UnitySilverlightApp.ProductService.ProductCategoryDTO category, object userState) {
            if ((this.onBeginGetSubcategoriesByCategoryDelegate == null)) {
                this.onBeginGetSubcategoriesByCategoryDelegate = new BeginOperationDelegate(this.OnBeginGetSubcategoriesByCategory);
            }
            if ((this.onEndGetSubcategoriesByCategoryDelegate == null)) {
                this.onEndGetSubcategoriesByCategoryDelegate = new EndOperationDelegate(this.OnEndGetSubcategoriesByCategory);
            }
            if ((this.onGetSubcategoriesByCategoryCompletedDelegate == null)) {
                this.onGetSubcategoriesByCategoryCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSubcategoriesByCategoryCompleted);
            }
            base.InvokeAsync(this.onBeginGetSubcategoriesByCategoryDelegate, new object[] {
                        category}, this.onEndGetSubcategoriesByCategoryDelegate, this.onGetSubcategoriesByCategoryCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override UnitySilverlightApp.ProductService.IProductService CreateChannel() {
            return new ProductServiceClientChannel(this);
        }
        
        private class ProductServiceClientChannel : ChannelBase<UnitySilverlightApp.ProductService.IProductService>, UnitySilverlightApp.ProductService.IProductService {
            
            public ProductServiceClientChannel(System.ServiceModel.ClientBase<UnitySilverlightApp.ProductService.IProductService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetProducts(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetProducts", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductDTO> EndGetProducts(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductDTO> _result = ((System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductDTO>)(base.EndInvoke("GetProducts", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetProduct(int productId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = productId;
                System.IAsyncResult _result = base.BeginInvoke("GetProduct", _args, callback, asyncState);
                return _result;
            }
            
            public UnitySilverlightApp.ProductService.ProductDTO EndGetProduct(System.IAsyncResult result) {
                object[] _args = new object[0];
                UnitySilverlightApp.ProductService.ProductDTO _result = ((UnitySilverlightApp.ProductService.ProductDTO)(base.EndInvoke("GetProduct", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetProductsBySubcategory(UnitySilverlightApp.ProductService.ProductSubcategoryDTO subcategory, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = subcategory;
                System.IAsyncResult _result = base.BeginInvoke("GetProductsBySubcategory", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductDTO> EndGetProductsBySubcategory(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductDTO> _result = ((System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductDTO>)(base.EndInvoke("GetProductsBySubcategory", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetCategories(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetCategories", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductCategoryDTO> EndGetCategories(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductCategoryDTO> _result = ((System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductCategoryDTO>)(base.EndInvoke("GetCategories", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetSubcategories(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetSubcategories", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductSubcategoryDTO> EndGetSubcategories(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductSubcategoryDTO> _result = ((System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductSubcategoryDTO>)(base.EndInvoke("GetSubcategories", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetSubcategoriesByCategory(UnitySilverlightApp.ProductService.ProductCategoryDTO category, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = category;
                System.IAsyncResult _result = base.BeginInvoke("GetSubcategoriesByCategory", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductSubcategoryDTO> EndGetSubcategoriesByCategory(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductSubcategoryDTO> _result = ((System.Collections.Generic.List<UnitySilverlightApp.ProductService.ProductSubcategoryDTO>)(base.EndInvoke("GetSubcategoriesByCategory", _args, result)));
                return _result;
            }
        }
    }
}
